"""
Backward compatibility: config lives at top-level (src/config).
Re-exports so existing 'from cinemind.config import ...' still work.
"""
from config import (
    OPENAI_API_KEY,
    TAVILY_API_KEY,
    is_tmdb_enabled,
    get_tmdb_access_token,
    TMDB_POSTER_MODE,
    ENABLE_TMDB_SCENES,
    TMDB_READ_ACCESS_TOKEN,
    AGENT_NAME,
    AGENT_VERSION,
    OPENAI_MODEL,
    SEARCH_PROVIDERS,
    KAGGLE_CORRELATION_THRESHOLD,
    KAGGLE_DATASET_PATH,
    ENABLE_KAGGLE_SEARCH,
    MOVIE_DATA_SOURCES,
    PROMPT_VERSION,
    REAL_AGENT_TIMEOUT_SECONDS,
    REAL_AGENT_MAX_TOKENS,
    REAL_AGENT_MAX_TOOL_CALLS,
    get_system_prompt,
    SYSTEM_PROMPT,
)

__all__ = [
    "OPENAI_API_KEY",
    "TAVILY_API_KEY",
    "is_tmdb_enabled",
    "get_tmdb_access_token",
    "TMDB_POSTER_MODE",
    "ENABLE_TMDB_SCENES",
    "TMDB_READ_ACCESS_TOKEN",
    "AGENT_NAME",
    "AGENT_VERSION",
    "OPENAI_MODEL",
    "SEARCH_PROVIDERS",
    "KAGGLE_CORRELATION_THRESHOLD",
    "KAGGLE_DATASET_PATH",
    "ENABLE_KAGGLE_SEARCH",
    "MOVIE_DATA_SOURCES",
    "PROMPT_VERSION",
    "REAL_AGENT_TIMEOUT_SECONDS",
    "REAL_AGENT_MAX_TOKENS",
    "REAL_AGENT_MAX_TOOL_CALLS",
    "get_system_prompt",
    "SYSTEM_PROMPT",
]
